# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View_JSON_XML.ui'
#
# Created: Thu Oct 19 09:39:36 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(746, 565)
        Form.setFocusPolicy(QtCore.Qt.WheelFocus)
        Form.setWindowOpacity(1.0)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtGui.QTextBrowser(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.JSON = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JSON.sizePolicy().hasHeightForWidth())
        self.JSON.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.JSON.setFont(font)
        self.JSON.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.JSON.setAutoFillBackground(False)
        self.JSON.setTextFormat(QtCore.Qt.AutoText)
        self.JSON.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.JSON.setObjectName("JSON")
        self.horizontalLayout_4.addWidget(self.JSON)
        self.slider = QtGui.QSlider(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider.sizePolicy().hasHeightForWidth())
        self.slider.setSizePolicy(sizePolicy)
        self.slider.setCursor(QtCore.Qt.ArrowCursor)
        self.slider.setMouseTracking(False)
        self.slider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider.setMaximum(1)
        self.slider.setTracking(True)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setInvertedAppearance(False)
        self.slider.setInvertedControls(False)
        self.slider.setObjectName("slider")
        self.horizontalLayout_4.addWidget(self.slider)
        self.XML = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.XML.setFont(font)
        self.XML.setObjectName("XML")
        self.horizontalLayout_4.addWidget(self.XML)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bSubmit = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSubmit.sizePolicy().hasHeightForWidth())
        self.bSubmit.setSizePolicy(sizePolicy)
        self.bSubmit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.bSubmit.setFont(font)
        self.bSubmit.setCursor(QtCore.Qt.ArrowCursor)
        self.bSubmit.setAutoDefault(True)
        self.bSubmit.setObjectName("bSubmit")
        self.horizontalLayout.addWidget(self.bSubmit)
        self.bReset = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bReset.sizePolicy().hasHeightForWidth())
        self.bReset.setSizePolicy(sizePolicy)
        self.bReset.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.bReset.setFont(font)
        self.bReset.setCursor(QtCore.Qt.ArrowCursor)
        self.bReset.setAutoDefault(True)
        self.bReset.setObjectName("bReset")
        self.horizontalLayout.addWidget(self.bReset)
        self.bClose = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bClose.sizePolicy().hasHeightForWidth())
        self.bClose.setSizePolicy(sizePolicy)
        self.bClose.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.bClose.setFont(font)
        self.bClose.setCursor(QtCore.Qt.ArrowCursor)
        self.bClose.setAutoDefault(True)
        self.bClose.setObjectName("bClose")
        self.horizontalLayout.addWidget(self.bClose)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lStart = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lStart.setFont(font)
        self.lStart.setObjectName("lStart")
        self.verticalLayout_4.addWidget(self.lStart)
        self.lZiel = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lZiel.setFont(font)
        self.lZiel.setObjectName("lZiel")
        self.verticalLayout_4.addWidget(self.lZiel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tStart = QtGui.QLineEdit(Form)
        self.tStart.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.tStart.setFont(font)
        self.tStart.setFrame(True)
        self.tStart.setEchoMode(QtGui.QLineEdit.Normal)
        self.tStart.setDragEnabled(False)
        self.tStart.setObjectName("tStart")
        self.verticalLayout_3.addWidget(self.tStart)
        self.tZiel = QtGui.QLineEdit(Form)
        self.tZiel.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.tZiel.setFont(font)
        self.tZiel.setObjectName("tZiel")
        self.verticalLayout_3.addWidget(self.tZiel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.status = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.horizontalLayout_3.addWidget(self.status)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.lStart.setBuddy(self.tStart)
        self.lZiel.setBuddy(self.tZiel)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.bClose, QtCore.SIGNAL("clicked()"), Form.close)
        QtCore.QObject.connect(self.bReset, QtCore.SIGNAL("clicked()"), self.tStart.clear)
        QtCore.QObject.connect(self.bReset, QtCore.SIGNAL("clicked()"), self.tZiel.clear)
        QtCore.QObject.connect(self.bReset, QtCore.SIGNAL("clicked()"), self.textBrowser.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tStart, self.tZiel)
        Form.setTabOrder(self.tZiel, self.bSubmit)
        Form.setTabOrder(self.bSubmit, self.bReset)
        Form.setTabOrder(self.bReset, self.bClose)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "( ͡° ͜ʖ ͡°)", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.JSON.setText(QtGui.QApplication.translate("Form", "JSON", None, QtGui.QApplication.UnicodeUTF8))
        self.XML.setText(QtGui.QApplication.translate("Form", "XML", None, QtGui.QApplication.UnicodeUTF8))
        self.bSubmit.setText(QtGui.QApplication.translate("Form", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.bReset.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.bClose.setText(QtGui.QApplication.translate("Form", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.lStart.setText(QtGui.QApplication.translate("Form", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.lZiel.setText(QtGui.QApplication.translate("Form", "Ziel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Berechnung:", None, QtGui.QApplication.UnicodeUTF8))

